import type { UiIR, UiNode, UiAttr } from '../types.js';

export function emitCSR(ui: UiIR): { code: string; map?: unknown } {
  const payload = {
    mode: 'csr',
    fileId: ui.fileId,
    dynCount: ui.dynCount,
    cssClasses: ui.cssClasses,
    roots: ui.roots.map((root) => ({
      exportName: root.exportName,
      range: root.range,
      tree: root.tree.map(sanitizeNode),
    })),
  };

  const code = `// Generated by Bridge compiler (CSR hydration spec)\nexport default ${JSON.stringify(payload, null, 2)};`;
  return { code };
}

function sanitizeNode(node: UiNode): unknown {
  switch (node.kind) {
    case 'Element':
      return {
        kind: node.kind,
        id: node.id,
        tag: node.tag,
        static: node.static,
        range: node.range,
        attrs: node.attrs.map(sanitizeAttr),
        children: node.children.map(sanitizeNode),
      };
    case 'Text':
      return {
        kind: node.kind,
        id: node.id,
        value: node.value,
        static: node.static,
        range: node.range,
      };
    case 'Hole':
      return {
        kind: node.kind,
        id: node.id,
        dynKind: node.dynKind,
        expr: node.expr,
        memo: node.memo ?? false,
        source: node.source,
        range: node.range,
      };
    case 'List':
      return {
        kind: node.kind,
        id: node.id,
        each: node.each,
        key: node.key,
        range: node.range,
        template: node.template.map(sanitizeNode),
      };
    case 'If':
      return {
        kind: node.kind,
        id: node.id,
        test: node.test,
        range: node.range,
        consequent: node.consequent.map(sanitizeNode),
        alternate: node.alternate ? node.alternate.map(sanitizeNode) : null,
      };
    default:
      return node;
  }
}

function sanitizeAttr(attr: UiAttr): unknown {
  if (attr.static) {
    return attr;
  }
  return {
    name: attr.name,
    static: false,
    expr: attr.expr,
    range: attr.range,
    source: attr.source,
    memo: attr.memo ?? false,
  };
}
